### ISSUE TITLE
Denmark missing

### ISSUE THREAD

**Issue by markbrough** [andylolz/org-id-finder#9] opened 2018-05-30 21:54 UTC
Denmark is missing from the list even though it has an organisation identifier: https://iatiregistry.org/publisher/danida

Org file looks ok to me?

Also... do you use the organisation identifier listed on the Registry? A lot of organisation identifiers are also provided there and I think the Secretariat was making some effort to reach out to publishers to keep these up to date. Might be cool

**Comment by andylolz** [comment] 2018-07-13 12:53
Hi @markbrough! Not sure if I missed this or replied to you directly? Either way, I’ll reply here for posterity

> Denmark is missing from the list even though it has an organisation identifier: https://iatiregistry.org/publisher/danida
>
> Org file looks ok to me?

As per @stevieflow’s algorithm, org-id-finder only shows self-reported identifiers – i.e. those for which the `organisation-identifier` matches the `reporting-org` reference.

In the case of Denmark MFA, the `organisation-identifier` provided is “XM-DAC-3-1”, but the `reporting-org` ref provided is “XI-IATI” (which is presumably a mistake). Indeed the `reporting-org` narrative provided is “International Aid Transparency Initiative Organisation Identifier”, which is definitely wrong.

They do appear in the [API](https://morph.io/documentation/api?scraper=andylolz%2Forg-id-finder) and [CSV download](https://api.morph.io/andylolz/org-id-finder/data.csv?key=wFTSIH61nwMjLBhphd4T&query=select%20org_id%2C%20name%2C%20lang%2C%20name_en%2C%20self_reported%2C%20source_dataset%2C%20source_url%2C%20valid_org_id%2C%20updated_at%20from%20organisations), but with `self-reported` set to false.

> Also... do you use the organisation identifier listed on the Registry? A lot of organisation identifiers are also provided there and I think the Secretariat was making some effort to reach out to publishers to keep these up to date. Might be cool

No… But which ones do you mean, exactly? In the publisher metadata? I suspect Steven looked into this, and I suspect he discovered that they’re often wrong… My ideal would be for the registry to populate this metadata from the data in the org file, so it doesn’t get out of sync.

Closing this issue just because I don’t think it’s expected behaviour (and is an issue with Denmark MFA data), but do feel free to comment!

**Closed by andylolz** 2018-07-13 12:53 UTC
